# Generated by Django 4.2.2 on 2023-07-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videoshare", "0002_videoupload"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videoupload",
            name="public",
        ),
        migrations.AddField(
            model_name="videoupload",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
