# Generated by Django 4.2.2 on 2023-07-10 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videoshare", "0003_remove_videoupload_public_videoupload_private"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoupload",
            name="video",
            field=models.FileField(
                upload_to="media/uploads/videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4"]
                    )
                ],
            ),
        ),
    ]
