# Generated by Django 4.2.2 on 2023-07-13 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videoshare", "0004_alter_videoupload_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoupload",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/images/"),
        ),
        migrations.AlterField(
            model_name="videoupload",
            name="video",
            field=models.FileField(
                upload_to="uploads/videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4"]
                    )
                ],
            ),
        ),
    ]
