# Generated by Django 4.2.2 on 2023-07-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videoshare", "0005_alter_videoupload_thumbnail_alter_videoupload_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoupload",
            name="video_id",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
