# Generated by Django 4.2.2 on 2023-07-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videoshare", "0006_videoupload_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoupload",
            name="video_id",
            field=models.CharField(max_length=120),
        ),
    ]
