# Generated by Django 4.2.2 on 2023-07-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videoshare", "0007_alter_videoupload_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoupload",
            name="video",
            field=models.FileField(upload_to="uploads/videos/"),
        ),
    ]
