# Generated by Django 4.2.2 on 2023-07-15 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("videoshare", "0009_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
