# Generated by Django 4.2.2 on 2023-07-15 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videoshare", "0010_like_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.AddField(
            model_name="like",
            name="dislikes",
            field=models.ManyToManyField(
                related_name="Video_dislikes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="likes",
            field=models.ManyToManyField(
                related_name="Video_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
