# Generated by Django 4.2.2 on 2023-07-15 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videoshare", "0011_remove_like_user_like_dislikes_like_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="like",
            name="likes",
        ),
        migrations.AddField(
            model_name="like",
            name="disliked_by",
            field=models.ManyToManyField(
                related_name="video_dislikes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="liked_by",
            field=models.ManyToManyField(
                related_name="video_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
