# Generated by Django 4.2.3 on 2023-07-17 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("videoshare", "0013_alter_like_disliked_by_alter_like_liked_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Views",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views", models.IntegerField(default=0)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="videoshare.videoupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Views",
                "verbose_name_plural": "Views",
            },
        ),
        migrations.CreateModel(
            name="UserViewHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("videos", models.ManyToManyField(to="videoshare.videoupload")),
            ],
            options={
                "verbose_name": "UserViewHistory",
                "verbose_name_plural": "UserViewHistorys",
            },
        ),
    ]
