# Generated by Django 4.2.3 on 2023-07-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videoshare", "0015_videoupload_views_delete_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userviewhistory",
            name="videos",
            field=models.ManyToManyField(blank=True, to="videoshare.videoupload"),
        ),
    ]
