# Generated by Django 4.2.3 on 2023-07-17 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("videoshare", "0016_alter_userviewhistory_videos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views", models.IntegerField(default=0)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="videoshare.videoupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trending",
                "verbose_name_plural": "Trendings",
            },
        ),
    ]
