# Generated by Django 4.2.3 on 2023-07-18 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("videoshare", "0017_trending"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Trending",
        ),
    ]
