# Generated by Django 4.2.3 on 2023-07-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoshare', '0019_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
