# Generated by Django 4.2.3 on 2023-07-24 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videoshare", "0021_commentlike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentlike",
            name="user",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
